### ISSUE TITLE
My free2z profile not showing up as funded...

### ISSUE THREAD

**Issue by tallship** [skyl/free2z#6]
Hi, 

My profile isn't showing up as funded. I actually attempted to fund it myself from my profile page (Fund Creator icon) using my ZecWallet-Lite, but then after sending, I realized that it would only go back to my same Shielded ZEC addy in that same wallet. I don't understand how this verification of funding works if it just passes through the entire transaction to my wallet address anyway.

So I saw another option under my profile, to: "Promote on F2Z" (the pink flower icon). I sent 0.01 ZEC to that address, and here is the transaction: https://zcha.in/transactions/43a11fce00f87a1eb8cc1175ac04d54cf4b381c2f02bb1fca1f639d306dd7f5a

I read in the docs that initial funding is 0.001 ZEC, and full funding unlocking all features is 0.01 ZEC (which I sent, and included a memo w/a reply to address as well). 

How long does this take before my profile is active? My profile is https://free2z.cash/tallship

Please advise :)

Thank you in advance, for your assistance in this matter.

**Comment by skyl** [comment]
Hey @tallship , thanks for the report -  I see your transaction and can credit it. The problem is that the memo should be JSON but it looks like you added a reply-to which the backend can't currently parse:

```
'{"act":"page_fund","id":"e67c47db-e1db-4b4f-a90b-365f02d51a53"}\nReply-To:\nzs1vp65edv7etxe2srwy76eqef0ulx3cth5x0fu60fm24rsneksts60qfpln24kmu4jx7vrge895ty'
```

I can potentially update the backend so that it could still find the JSON payload. But, in general funding won't work if the memo is changed from what is in the zip321 URI.
